import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy — Cards of Magic',
  description: 'Privacy Policy for Cards of Magic Telegram Mini App',
};

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-[#0d0b1a] via-[#13102a] to-[#0d0b1a] text-[#e0d8f0]">
      {/* Decorative top */}
      <div className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-purple-900/20 to-transparent" />
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-96 h-96 bg-purple-600/10 rounded-full blur-3xl" />
        <div className="relative z-10 max-w-2xl mx-auto px-6 pt-16 pb-8 text-center">
          <p className="text-4xl mb-3">🔮</p>
          <h1 className="text-3xl font-bold bg-gradient-to-r from-purple-300 via-amber-200 to-purple-300 bg-clip-text text-transparent">
            Privacy Policy
          </h1>
          <p className="text-sm text-purple-300/60 mt-2">Cards of Magic — Telegram Mini App</p>
          <p className="text-xs text-purple-300/40 mt-1">Last updated: June 19, 2026</p>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-2xl mx-auto px-6 pb-20 space-y-8">
        <Section title="1. Introduction">
          <p>
            Welcome to <b>Cards of Magic</b> (&quot;we&quot;, &quot;our&quot;, &quot;the App&quot;). This Privacy Policy
            explains how we collect, use, and protect your personal information when you use our
            Telegram Mini App for tarot readings and esoteric services.
          </p>
          <p>
            By using Cards of Magic, you agree to the collection and use of information in accordance
            with this policy.
          </p>
        </Section>

        <Section title="2. Information We Collect">
          <Subsection title="2.1 Telegram Profile Data">
            <p>When you open the App through Telegram, we receive:</p>
            <ul className="list-disc list-inside space-y-1 ml-2 text-sm">
              <li>Your Telegram user ID</li>
              <li>First name and last name</li>
              <li>Username (if set)</li>
              <li>Language preference</li>
              <li>Profile photo URL (if public)</li>
            </ul>
            <p className="text-xs text-purple-300/50 mt-1">
              This data is provided by Telegram&apos;s Mini App platform and is necessary for the App to function.
            </p>
          </Subsection>

          <Subsection title="2.2 Usage Data">
            <p>We store the following data related to your activity:</p>
            <ul className="list-disc list-inside space-y-1 ml-2 text-sm">
              <li>Tarot readings and their interpretations</li>
              <li>Card collection progress</li>
              <li>Mana balance and transaction history</li>
              <li>Daily login streaks</li>
              <li>Subscription status</li>
            </ul>
          </Subsection>

          <Subsection title="2.3 Payment Data">
            <p>
              Payments are processed exclusively through <b>Telegram Stars</b>. We do not collect,
              store, or have access to your financial information such as credit card numbers or
              bank details. All payment processing is handled by Telegram.
            </p>
          </Subsection>
        </Section>

        <Section title="3. How We Use Your Information">
          <ul className="list-disc list-inside space-y-2 ml-2 text-sm">
            <li>To provide personalized tarot readings and esoteric services</li>
            <li>To maintain your account, progress, and card collection</li>
            <li>To manage the mana economy and subscription features</li>
            <li>To enable the daily card, streaks, and achievement systems</li>
            <li>To process referral bonuses</li>
            <li>To respond to support inquiries</li>
            <li>To improve the App experience</li>
          </ul>
        </Section>

        <Section title="4. Data Storage & Security">
          <p>
            Your data is stored on secure servers with encryption in transit (TLS/SSL). We use
            industry-standard security measures to protect your personal information. Database
            access is restricted and monitored.
          </p>
          <p>
            Reading interpretations are generated by AI models and are not reviewed by humans
            unless you contact support.
          </p>
        </Section>

        <Section title="5. Third-Party Services">
          <p>We use the following third-party services:</p>
          <ul className="list-disc list-inside space-y-1 ml-2 text-sm">
            <li><b>Telegram</b> — Platform, authentication, and payments</li>
            <li><b>Vercel</b> — Application hosting</li>
            <li><b>AI Language Models</b> — For generating reading interpretations</li>
          </ul>
          <p>
            Each service has its own privacy policy. We recommend reviewing them for complete
            information about their data practices.
          </p>
        </Section>

        <Section title="6. Data Sharing">
          <p>
            We do <b>not</b> sell, rent, or share your personal information with third parties for
            marketing purposes. Your reading history and personal data are private and visible
            only to you.
          </p>
          <p>
            Support messages may be reviewed by our team to provide assistance.
          </p>
        </Section>

        <Section title="7. Data Retention">
          <p>
            Your data is retained as long as you use the App. If you wish to delete your account
            and all associated data, please contact our support through the App.
          </p>
        </Section>

        <Section title="8. Your Rights">
          <p>You have the right to:</p>
          <ul className="list-disc list-inside space-y-1 ml-2 text-sm">
            <li>Access your personal data</li>
            <li>Request correction of inaccurate data</li>
            <li>Request deletion of your data</li>
            <li>Withdraw consent at any time by stopping use of the App</li>
          </ul>
          <p>
            To exercise these rights, contact us through the in-app support feature.
          </p>
        </Section>

        <Section title="9. Children's Privacy">
          <p>
            Cards of Magic is not intended for users under the age of 13. We do not knowingly
            collect personal information from children. If you believe a child has provided us
            with personal data, please contact support for removal.
          </p>
        </Section>

        <Section title="10. Changes to This Policy">
          <p>
            We may update this Privacy Policy from time to time. Changes will be posted on this
            page with an updated revision date. Continued use of the App after changes constitutes
            acceptance of the updated policy.
          </p>
        </Section>

        <Section title="11. Contact Us">
          <p>
            If you have questions about this Privacy Policy, contact us through:
          </p>
          <ul className="list-disc list-inside space-y-1 ml-2 text-sm">
            <li>In-app support (💬 icon)</li>
            <li>
              Telegram: <a href="https://t.me/cardsofmagicsupport_bot" className="text-purple-300 hover:text-purple-200 underline">@cardsofmagicsupport_bot</a>
            </li>
          </ul>
        </Section>

        {/* Footer */}
        <div className="pt-8 border-t border-purple-500/10 text-center">
          <p className="text-xs text-purple-300/30">
            © 2026 Cards of Magic. All rights reserved.
          </p>
          <p className="text-2xl mt-3 opacity-30">🔮✨🃏</p>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-lg font-semibold text-purple-200 mb-3 flex items-center gap-2">
        <span className="w-1 h-5 bg-gradient-to-b from-purple-400 to-purple-600 rounded-full inline-block" />
        {title}
      </h2>
      <div className="space-y-3 text-sm leading-relaxed text-[#c0b8d8]">{children}</div>
    </section>
  );
}

function Subsection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="ml-3 mt-2">
      <h3 className="text-sm font-medium text-purple-300/80 mb-1">{title}</h3>
      <div className="space-y-2">{children}</div>
    </div>
  );
}
